### ISSUE TITLE
Removes whitespace from calc in CSS

### ISSUE THREAD

**Issue by stephenwf** [sstephenson/ruby-yui-compressor#42]
Hi given the following CSS:

```
width: calc(100% + 20px);
```

the compressor gives:

```
width: calc(100%+20px);
```

Which is not valid CSS.

**Comment by stevecrozz** [comment]
@stephenwf This issue is already fixed upstream, but yuicompressor hasn't released a new version for almost two years. Unfortunately we have to wait on them to release the fix before we can use it here. You could try following up with the maintainer about the next release: https://groups.google.com/forum/?fromgroups=#!topic/yuicompressor/_AODsghvFzU
